// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9ARCWKc-ip7vvXyS22cW7JazEmzpM58',
    appId: '1:1018433624543:web:ce50fd8de656193303cc6a',
    messagingSenderId: '1018433624543',
    projectId: 'schoolify-7c11a',
    authDomain: 'schoolify-7c11a.firebaseapp.com',
    storageBucket: 'schoolify-7c11a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrkDGzlK_-52n0zWuK7eWAI4ipBlinvE',
    appId: '1:1018433624543:android:7d000d5758e767ae03cc6a',
    messagingSenderId: '1018433624543',
    projectId: 'schoolify-7c11a',
    storageBucket: 'schoolify-7c11a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvLFQA7JVXsI9dBQyZ2RjTo6KXxEoTsw',
    appId: '1:1018433624543:ios:aadc993060c6aa8003cc6a',
    messagingSenderId: '1018433624543',
    projectId: 'schoolify-7c11a',
    storageBucket: 'schoolify-7c11a.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCvLFQA7JVXsI9dBQyZ2RjTo6KXxEoTsw',
    appId: '1:1018433624543:ios:aadc993060c6aa8003cc6a',
    messagingSenderId: '1018433624543',
    projectId: 'schoolify-7c11a',
    storageBucket: 'schoolify-7c11a.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm9ARCWKc-ip7vvXyS22cW7JazEmzpM58',
    appId: '1:1018433624543:web:e7efc87a19cb88be03cc6a',
    messagingSenderId: '1018433624543',
    projectId: 'schoolify-7c11a',
    authDomain: 'schoolify-7c11a.firebaseapp.com',
    storageBucket: 'schoolify-7c11a.firebasestorage.app',
  );
}
